version: '3.2'

services:
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,z
      - elasticsearch:/usr/share/elasticsearch/data:z
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx1024m -Xms1024m"
      ELASTIC_PASSWORD: changeme
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      #discovery.type: single-node
      node.name: elasticsearch
      discovery.seed_hosts: elasticsearch-master
      cluster.initial_master_nodes: elasticsearch-master
    networks:
      - elk

  elasticsearch-ingest:
    build:
      context: elasticsearch-ingest/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./elasticsearch-ingest/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,z
    ports:
      - "9201:9200"
      - "9301:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx1024m -Xms1024m"
      ELASTIC_PASSWORD: changeme
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      #discovery.type: single-node
      node.name: elasticsearch-ingest
      discovery.seed_hosts: elasticsearch-master
      cluster.initial_master_nodes: elasticsearch-master
    networks:
      - elk

  elasticsearch-query:
    build:
      context: elasticsearch-query/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./elasticsearch-query/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,z
      - ./elasticsearch-query/config/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties:ro,z
      - ./mounted_logs:/usr/share/elasticsearch/logs/mounted_logs:rw,z
    ports:
      - "9202:9200"
      - "9302:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx1024m -Xms1024m"
      ELASTIC_PASSWORD: changeme
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      #discovery.type: single-node
      node.name: elasticsearch-query
      discovery.seed_hosts: elasticsearch-master
      cluster.initial_master_nodes: elasticsearch-master
    networks:
      - elk

  elasticsearch-master:
    build:
      context: elasticsearch-master/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./elasticsearch-master/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,z
    ports:
      - "9203:9200"
      - "9303:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx1024m -Xms1024m"
      ELASTIC_PASSWORD: changeme
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      #discovery.type: single-node
      node.name: elasticsearch-master
      discovery.seed_hosts: elasticsearch-master
      cluster.initial_master_nodes: elasticsearch-master
    networks:
      - elk

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,z
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro,z
      - ./mounted_logs:/mounted_logs:ro,z
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx1024m -Xms1024m"
    networks:
      - elk
    depends_on:
      - elasticsearch-ingest

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,z
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:
