---
## Default Kibana configuration from Kibana base image.
## https://github.com/elastic/kibana/blob/master/src/dev/build/tasks/os_packages/docker_generator/templates/kibana_yml.template.ts
#
server.name: kibana
server.host: 0.0.0.0
elasticsearch.hosts: [ "http://elasticsearch-query:9200" ]
monitoring.ui.container.elasticsearch.enabled: true

## X-Pack security credentials
#
elasticsearch.username: elastic
elasticsearch.password: changeme

#xpack.security.audit.enabled: true
#xpack.security.audit.appender:
#  type: rolling-file
#  fileName: audit.log
#  policy:
#    type: time-interval
#    interval: 24h
#  strategy:
#    type: numeric
#    max: 10
#  layout:
#    type: json


# Export security audit log to system index
#xpack.security.audit.outputs: index
# Export http request body to audit log
#xpack.security.audit.index.events.emit_request_body: true
